ALTER TABLE items ADD COLUMN ai_summary TEXT NOT NULL DEFAULT '';
ALTER TABLE items ADD COLUMN title_zh TEXT NOT NULL DEFAULT '';
ALTER TABLE items ADD COLUMN abstract_zh TEXT NOT NULL DEFAULT '';
ALTER TABLE items ADD COLUMN core_contribution TEXT NOT NULL DEFAULT '';
ALTER TABLE items ADD COLUMN method TEXT NOT NULL DEFAULT '';
ALTER TABLE items ADD COLUMN result TEXT NOT NULL DEFAULT '';
ALTER TABLE items ADD COLUMN limitations TEXT NOT NULL DEFAULT '';
